dataapp:
  store:
    redis:
      type: 0
      host: "localhost:6379"
    mongo:
      host: "mongodb://localhost:27017/"
  mq:
    nats_streaming:
      url: "nats://localhost:4222"
      cluster_id: "nats-cluster"
      client_id: "dataapp-sync"
      durable: "mongo-data-msg"
      subject: "mongosync"
    kafka:
      host: ""
      
      

    


